name: heal_her
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  calendar_date_picker2: ^0.5.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.15
  flutter_datetime_picker_bdaya: ^3.0.2
  flutter_ruler_picker: 1.0.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  get_it: ^7.6.7
  hive: ^2.2.3
  http: ^1.2.1
  intl: ^0.18.1
  mongo_dart: ^0.10.0
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  real_time_chart: ^0.0.1
  scroll_snap_list: ^0.9.1
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/
    - assets/png/
    - assets/

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/font.ttf
