name: heal_her
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  calendar_date_picker2: ^0.5.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_bdaya: ^3.0.2
  flutter_ruler_picker: ^1.0.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  hive: ^2.2.3
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  scroll_snap_list: ^0.9.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/activity_images/
    - assets/images/targets_images/
    - assets/fonts/
    - assets/svg/
    - assets/png/
    - assets/
    - assets/gif/

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/font.ttf
